AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - '.git/**/*'
    - 'bin/*'
    - 'spec/example/db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'podling.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100
  AllowURI: true
  IgnoredPatterns:
    - '\A\s*#'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'spec/example/bin/*'

Style/NumericLiterals:
  Exclude:
    - 'spec/example/db/schema.rb'
